
services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    expose:
      - "3306"
    restart: always

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - site:/var/www/html
    restart: always

  wordpress:
    container_name: wordpress
    env_file: .env
    networks:
      - inception
    volumes:
      - site:/var/www/html
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: always
    expose:
      - "9000"

volumes:
  site:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/home/atomasi/data/wordpress"
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/home/atomasi/data/mariadb"

networks:
  inception:
    driver: bridge


#
#nginx_off:
#    image: nginx:latest
#    container_name: nginx_off
#    env_file: .env
#    networks:
#      - inception
#    ports:
#      - "443:443"
#    depends_on:
#      - wordpress_off
#    volumes:
#      - site:/var/www/html
#      - ./requirements/nginx/config/certif:/etc/nginx/ssl
#      - ./requirements/nginx/config/:/etc/nginx/conf.d
#    restart: always
