version: "3"

services:
  mariadb_off:
    image: mariadb:latest
    container_name: mariadb_off
    env_file: .env
    networks:
      - inception
    volumes:
      - db:database/
    expose:
      - "3306"
    restart: alaways

  nginx_off:
    image: nginx:latest
    container_name: nginx_off
    env_file: .env
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress_off
    volumes:
      - site:www/
    restart: alaways

  wordpress_off:
    image: wordpress:latest
    container_name: mariadb_off
    env_file: .env
    networks:
      - inception
    volumes:
      - site:srcs/
    depends_on:
      - mariadb_off
    restart: alaways
    expose:
      - "9000"

volumes:
  site:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/home/atomasi/data/site"
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "/home/atomasi/data/db"

networks:
  inception:
    driver: bridge
